# This is a basic workflow to help you get started with Actions

name: push changes to second repo

# Controls when the action will run. 
on:
  # Triggers the workflow pull requests merged to the main branch
  pull_request:
    branches: 
      - main 
    types:  
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository:  site-policy 

      # Pushes to other repo 
      - name: GitHub Action to Push Subdirectories to Another Repo
        uses: johno/actions-push-subdirectories@v0.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # accepts two required args and two optional: [folder] [username] [repository name] [branch changes pushed to, defaults to main]
          args: Policies pcihon test

